# bash aliases
diff='diff --color=auto'
egrep='egrep --color=auto'
fgrep='fgrep --color=auto'
grep='grep --color=auto'
history='history 0'
ip='ip --color=auto'
l='ls -CF'
la='ls -A'
ll='ls -l'
ls='ls --color=auto'
#which-command=whence
## added by me
alias lt='ls --human-readable --size -1 -S --classify'
alias va='source .venv/bin/activate'
alias ve='virtualenv .venv'
alias xclip='xclip -selection clipboard'
alias conpty='stty raw -echo; (stty size; cat) | nc -lvnp '
alias nmapfull='sudo nmap -sC -sV -p- -oA nmap/Full -vvv $IP'
alias nmapudp='sudo nmap -sU --min-rate 10000 $IP'
